### ISSUE TITLE
Failed rendering frame

### ISSUE THREAD

**Issue by tearscoco** [EvelynFan/FaceFormer#7]
Hi,

I am facing a Failed rendering frame issue with the following error: 
"cannot import name 'OSMesaCreateContextAttribs' from 'OpenGL.osmesa'"

I'm with CentOS, and I have installed both openGL and Libosmesa, but this issue still appears. Could you please help have a look at it?

**Comment by EvelynFan** [comment]
> Hi,
> 
> I am facing a Failed rendering frame issue with the following error: "cannot import name 'OSMesaCreateContextAttribs' from 'OpenGL.osmesa'"
> 
> I'm with CentOS, and I have installed both openGL and Libosmesa, but this issue still appears. Could you please help have a look at it?

Hi, it seems that it's a common issue. The rendering script is borrowed from VOCA - Perhaps you can check the following two links for possible solutions:

https://github.com/TimoBolkart/voca/issues/60
https://github.com/TimoBolkart/voca/issues/46

**Comment by tearscoco** [comment]
Thanks for your quick response! I've searched almost all the possible solutions through google but still not been able to solve the issue. Suspect it's a compatible issue between CentOS and required libs. I will try to walk round this problem by using Ubuntu docker and will update this issue later :)

**Comment by khalidhnv** [comment]
i had this issue in ubuntu too and was resolved after following osmesa installation script https://pyrender.readthedocs.io/en/latest/install/index.html#installmesa. in case you have it even after following above steps, then it might be CentOs specific issue

**Comment by ujjawalcse** [comment]
I was facing the same issue and resolved using the hints given by @khalidhnv .
you can refer to my google colab notebook for  step by step installations and running demo.

https://colab.research.google.com/drive/11DB_KIE8A_u1qnu6xHtkOIRBiv50QnpR?usp=sharing

Please edit the runtime to use GPU for the notebook.

Thanks

**Comment by tearscoco** [comment]
Hi all,

I have resolved this issue by upgrading my pyopengl version to 3.1.4. Even though I got warning saying that pyrender fits the pyopengl version 3.1.0, I still continued to use 3.1.4 version!! It's weird but working somehow! Hope it helps you!

**Comment by HOMGH** [comment]
These steps resolved the rendering issue for me:

1. Set the environment variable:

   ```bash
   setenv PYOPENGL_PLATFORM egl
   ```

2. Upgrade PyOpenGL and PyOpenGL\_accelerate:

   ```bash
   pip install --upgrade PyOpenGL PyOpenGL_accelerate
   ```

3. In `demo.py`, make sure to set the environment variable in code:

   ```python
   import os
   os.environ['PYOPENGL_PLATFORM'] = 'egl'
   ```
